/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.Address;
import Model.Contact;
import Model.Person;

/**
 *
 * @author sruthisivasankar
 */
public class mainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainJFrame
     */
    private Person person;
    
    public mainJFrame() {
        initComponents();
        
        this.person = new Person();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        createPanel = new javax.swing.JPanel();
        labelFirstName = new javax.swing.JLabel();
        labelStreet = new javax.swing.JLabel();
        fieldName = new javax.swing.JTextField();
        fieldStreet = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        labelLastName = new javax.swing.JLabel();
        fieldLastname = new javax.swing.JTextField();
        labelCollege = new javax.swing.JLabel();
        fieldCollege = new javax.swing.JTextField();
        labelNuid = new javax.swing.JLabel();
        fieldNuid = new javax.swing.JTextField();
        labelPermaAdd = new javax.swing.JLabel();
        labelAptNo = new javax.swing.JLabel();
        fieldAptNo = new javax.swing.JTextField();
        labelCity = new javax.swing.JLabel();
        fieldCity = new javax.swing.JTextField();
        labelZip = new javax.swing.JLabel();
        fieldZip = new javax.swing.JTextField();
        labelCurrAdd = new javax.swing.JLabel();
        labelAptNo2 = new javax.swing.JLabel();
        fieldAptNo2 = new javax.swing.JTextField();
        labelStreet2 = new javax.swing.JLabel();
        fieldStreet2 = new javax.swing.JTextField();
        labelCity2 = new javax.swing.JLabel();
        fieldCity2 = new javax.swing.JTextField();
        labelZip2 = new javax.swing.JLabel();
        fieldZip2 = new javax.swing.JTextField();
        labelPersCont = new javax.swing.JLabel();
        labelPhone = new javax.swing.JLabel();
        fieldPhone = new javax.swing.JTextField();
        labelEmail = new javax.swing.JLabel();
        fieldEmail = new javax.swing.JTextField();
        labelOffCont = new javax.swing.JLabel();
        labelPhone2 = new javax.swing.JLabel();
        fieldPhone2 = new javax.swing.JTextField();
        labelEmail2 = new javax.swing.JLabel();
        fieldEmail2 = new javax.swing.JTextField();
        viewPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        viewName = new javax.swing.JLabel();
        viewStreet = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        viewLastname = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        viewCollege = new javax.swing.JLabel();
        viewNuid = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        viewAptNo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        viewCity = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        viewZip = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        viewAptNo2 = new javax.swing.JLabel();
        viewStreet2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        viewCity2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        viewZip2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        viewPhone = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        viewEmail = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        viewPhone2 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        viewEmail2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        createPanel.setBackground(new java.awt.Color(0, 204, 204));

        labelFirstName.setText("First Name:");

        labelStreet.setText("Street:");

        fieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNameActionPerformed(evt);
            }
        });

        saveButton.setBackground(new java.awt.Color(255, 51, 51));
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        labelLastName.setText("Last Name:");

        fieldLastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldLastnameActionPerformed(evt);
            }
        });

        labelCollege.setText("College:");

        labelNuid.setText("NUID:");

        labelPermaAdd.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        labelPermaAdd.setText("Permanent Address:");

        labelAptNo.setText("Apt no:");

        labelCity.setText("City/State:");

        labelZip.setText("Zip Code:");

        fieldZip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldZipActionPerformed(evt);
            }
        });

        labelCurrAdd.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        labelCurrAdd.setText("Current Address:");

        labelAptNo2.setText("Apt no:");

        fieldAptNo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldAptNo2ActionPerformed(evt);
            }
        });

        labelStreet2.setText("Street:");

        fieldStreet2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldStreet2ActionPerformed(evt);
            }
        });

        labelCity2.setText("City/State:");

        fieldCity2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCity2ActionPerformed(evt);
            }
        });

        labelZip2.setText("Zip Code:");

        fieldZip2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldZip2ActionPerformed(evt);
            }
        });

        labelPersCont.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        labelPersCont.setText("Personal Contact:");

        labelPhone.setText("Phone:");

        fieldPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPhoneActionPerformed(evt);
            }
        });

        labelEmail.setText("Email ID:");

        labelOffCont.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        labelOffCont.setText("Office Contact:");

        labelPhone2.setText("Phone:");

        labelEmail2.setText("Email ID:");

        javax.swing.GroupLayout createPanelLayout = new javax.swing.GroupLayout(createPanel);
        createPanel.setLayout(createPanelLayout);
        createPanelLayout.setHorizontalGroup(
            createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createPanelLayout.createSequentialGroup()
                        .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCity2)
                            .addComponent(labelPersCont)
                            .addComponent(labelPhone)
                            .addComponent(labelEmail)
                            .addComponent(labelOffCont)
                            .addComponent(labelPhone2)
                            .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(fieldCity2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                .addComponent(fieldAptNo2, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(0, 117, Short.MAX_VALUE))
                    .addGroup(createPanelLayout.createSequentialGroup()
                        .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, createPanelLayout.createSequentialGroup()
                                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(fieldCity, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                    .addComponent(labelAptNo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelCity, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelEmail2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldAptNo))
                                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(createPanelLayout.createSequentialGroup()
                                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createPanelLayout.createSequentialGroup()
                                                    .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(labelStreet)
                                                        .addComponent(labelZip)
                                                        .addComponent(labelStreet2)
                                                        .addComponent(labelZip2))
                                                    .addGap(37, 37, 37))
                                                .addComponent(fieldStreet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(fieldStreet2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(fieldZip, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(fieldPhone)
                                    .addComponent(fieldEmail)
                                    .addComponent(fieldPhone2)
                                    .addComponent(fieldEmail2)))
                            .addGroup(createPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createPanelLayout.createSequentialGroup()
                                                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(labelLastName)
                                                        .addComponent(labelCollege))
                                                    .addComponent(labelNuid, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(fieldLastname, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                                    .addComponent(fieldCollege)
                                                    .addComponent(fieldNuid)))
                                            .addComponent(labelCurrAdd)
                                            .addComponent(labelAptNo2))
                                        .addGroup(createPanelLayout.createSequentialGroup()
                                            .addComponent(labelFirstName)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(fieldName))
                                        .addComponent(labelPermaAdd))
                                    .addComponent(fieldZip2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())))
        );
        createPanelLayout.setVerticalGroup(
            createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFirstName)
                    .addComponent(fieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelLastName)
                    .addComponent(fieldLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCollege)
                    .addComponent(fieldCollege, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNuid)
                    .addComponent(fieldNuid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelPermaAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAptNo)
                    .addComponent(labelStreet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldAptNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCity)
                    .addComponent(labelZip, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(labelCurrAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAptNo2)
                    .addComponent(labelStreet2))
                .addGap(3, 3, 3)
                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldAptNo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldStreet2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCity2)
                    .addComponent(labelZip2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldCity2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldZip2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(labelPersCont)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPhone)
                    .addComponent(fieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmail)
                    .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelOffCont)
                .addGap(18, 18, 18)
                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPhone2)
                    .addComponent(fieldPhone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(createPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEmail2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(saveButton)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(createPanel);

        viewPanel.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setText("First Name:");

        jLabel2.setText("Street:");

        viewName.setText("jLabel3");

        viewStreet.setText("jLabel3");

        jLabel3.setText("Last Name:");

        viewLastname.setText("jLabel4");

        jLabel4.setText("College:");

        jLabel5.setText("NUID:");

        viewCollege.setText("jLabel6");

        viewNuid.setText("jLabel7");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel6.setText("Permanent Address:");

        jLabel7.setText("Apt No:");

        viewAptNo.setText("jLabel8");

        jLabel8.setText("City/State:");

        viewCity.setText("jLabel9");

        jLabel9.setText("Zip Code:");

        viewZip.setText("jLabel10");

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel10.setText("Current Address:");

        jLabel11.setText("Apt No:");

        jLabel12.setText("Street:");

        viewAptNo2.setText("jLabel13");

        viewStreet2.setText("jLabel13");

        jLabel13.setText("City/State:");

        viewCity2.setText("jLabel14");

        jLabel14.setText("Zip Code:");

        viewZip2.setText("jLabel15");

        jLabel15.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel15.setText("Personal Contact:");

        jLabel16.setText("Phone:");

        viewPhone.setText("jLabel17");

        jLabel17.setText("Email ID:");

        viewEmail.setText("jLabel18");

        jLabel18.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel18.setText("Office Contact:");

        jLabel19.setText("Phone:");

        viewPhone2.setText("jLabel20");

        jLabel20.setText("Email ID:");

        viewEmail2.setText("jLabel21");

        javax.swing.GroupLayout viewPanelLayout = new javax.swing.GroupLayout(viewPanel);
        viewPanel.setLayout(viewPanelLayout);
        viewPanelLayout.setHorizontalGroup(
            viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel15)
                    .addComponent(jLabel10)
                    .addComponent(jLabel6)
                    .addGroup(viewPanelLayout.createSequentialGroup()
                        .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(viewAptNo)
                            .addComponent(jLabel8)
                            .addComponent(viewCity)
                            .addComponent(jLabel11)
                            .addComponent(viewAptNo2)
                            .addComponent(jLabel13)
                            .addComponent(viewCity2)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addGap(65, 65, 65)
                        .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewEmail2)
                            .addComponent(viewPhone2)
                            .addComponent(viewEmail)
                            .addComponent(viewPhone)
                            .addComponent(viewZip2)
                            .addComponent(jLabel14)
                            .addComponent(jLabel12)
                            .addComponent(viewZip)
                            .addComponent(jLabel9)
                            .addComponent(viewNuid)
                            .addComponent(viewCollege)
                            .addComponent(viewLastname)
                            .addComponent(viewStreet)
                            .addComponent(viewName)
                            .addComponent(jLabel2)
                            .addComponent(viewStreet2))))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        viewPanelLayout.setVerticalGroup(
            viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPanelLayout.createSequentialGroup()
                .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewPanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(viewName))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(viewLastname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(viewCollege))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(viewNuid))
                .addGap(7, 7, 7)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewStreet)
                    .addComponent(viewAptNo))
                .addGap(18, 18, 18)
                .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewCity)
                    .addComponent(viewZip))
                .addGap(26, 26, 26)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewAptNo2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewStreet2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewCity2)
                    .addComponent(viewZip2))
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(viewPhone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(viewEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(viewPhone2))
                .addGap(18, 18, 18)
                .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewEmail2)
                    .addComponent(jLabel20))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(viewPanel);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        String firstname = fieldName.getText();
        String lastname = fieldLastname.getText();
        String college= fieldCollege.getText();
        String NUID = fieldNuid.getText();
        
        String apartNo=fieldAptNo.getText();
        String street = fieldStreet.getText();
        String city=fieldCity.getText();
        String zipCode=fieldZip.getText();
        
        String apartNo2 =fieldAptNo2.getText();
        String street2 = fieldStreet2.getText();
        String city2 = fieldCity2.getText();
        String zipCode2 = fieldZip2.getText();
        
        String phone= fieldPhone.getText();
        String emailId = fieldEmail.getText();
        
        String phone2 = fieldPhone2.getText();
        String emailId2 = fieldEmail2.getText();
        
        this.person.setFirstname(firstname);
        this.person.setLastname(lastname);
        this.person.setCollege(college);
        this.person.setNUID(NUID);
 
//        this.person.setAddress(address);
//        this.person.setContact(contact);
        
        Address permanentAddress = this.person.getPermanentAddress();
        permanentAddress.setStreetName(street);
        permanentAddress.setApartNo(apartNo);
        permanentAddress.setCity(city);
        permanentAddress.setZipCode(zipCode);
        
        Address currentAddress = this.person.getCurrentAddress();
        currentAddress.setStreetName(street2);
        currentAddress.setApartNo(apartNo2);
        currentAddress.setCity(city2);
        currentAddress.setZipCode(zipCode2);
        
        Contact personalContact=this.person.getPersonalContact();
        personalContact.setPhone(phone);
        personalContact.setEmailId(emailId);
        
        Contact officeContact=this.person.getOfficeContact();
        officeContact.setPhone(phone2);
        officeContact.setEmailId(emailId2);
               
        display();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void display(){
        viewName.setText(this.person.getFirstname());
        viewLastname.setText(this.person.getLastname());
        viewCollege.setText(this.person.getCollege());
        viewNuid.setText(this.person.getNUID());
        
        viewAptNo.setText(this.person.getPermanentAddress().getApartNo());
        viewStreet.setText(this.person.getPermanentAddress().getStreetName());
        viewCity.setText(this.person.getPermanentAddress().getCity());
        viewZip.setText(this.person.getPermanentAddress().getZipCode());
        
        viewAptNo2.setText(this.person.getCurrentAddress().getApartNo());
        viewStreet2.setText(this.person.getCurrentAddress().getStreetName());
        viewCity2.setText(this.person.getCurrentAddress().getCity());
        viewZip2.setText(this.person.getCurrentAddress().getZipCode());
        
        viewPhone.setText(this.person.getPersonalContact().getPhone());
        viewEmail.setText(this.person.getPersonalContact().getEmailId());
        
        viewPhone2.setText(this.person.getOfficeContact().getPhone());
        viewEmail2.setText(this.person.getOfficeContact().getEmailId());
    }
    private void fieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNameActionPerformed

    private void fieldLastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldLastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldLastnameActionPerformed

    private void fieldZipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldZipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldZipActionPerformed

    private void fieldAptNo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldAptNo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldAptNo2ActionPerformed

    private void fieldStreet2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldStreet2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldStreet2ActionPerformed

    private void fieldCity2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCity2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCity2ActionPerformed

    private void fieldZip2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldZip2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldZip2ActionPerformed

    private void fieldPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPhoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel createPanel;
    private javax.swing.JTextField fieldAptNo;
    private javax.swing.JTextField fieldAptNo2;
    private javax.swing.JTextField fieldCity;
    private javax.swing.JTextField fieldCity2;
    private javax.swing.JTextField fieldCollege;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JTextField fieldEmail2;
    private javax.swing.JTextField fieldLastname;
    private javax.swing.JTextField fieldName;
    private javax.swing.JTextField fieldNuid;
    private javax.swing.JTextField fieldPhone;
    private javax.swing.JTextField fieldPhone2;
    private javax.swing.JTextField fieldStreet;
    private javax.swing.JTextField fieldStreet2;
    private javax.swing.JTextField fieldZip;
    private javax.swing.JTextField fieldZip2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel labelAptNo;
    private javax.swing.JLabel labelAptNo2;
    private javax.swing.JLabel labelCity;
    private javax.swing.JLabel labelCity2;
    private javax.swing.JLabel labelCollege;
    private javax.swing.JLabel labelCurrAdd;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelEmail2;
    private javax.swing.JLabel labelFirstName;
    private javax.swing.JLabel labelLastName;
    private javax.swing.JLabel labelNuid;
    private javax.swing.JLabel labelOffCont;
    private javax.swing.JLabel labelPermaAdd;
    private javax.swing.JLabel labelPersCont;
    private javax.swing.JLabel labelPhone;
    private javax.swing.JLabel labelPhone2;
    private javax.swing.JLabel labelStreet;
    private javax.swing.JLabel labelStreet2;
    private javax.swing.JLabel labelZip;
    private javax.swing.JLabel labelZip2;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel viewAptNo;
    private javax.swing.JLabel viewAptNo2;
    private javax.swing.JLabel viewCity;
    private javax.swing.JLabel viewCity2;
    private javax.swing.JLabel viewCollege;
    private javax.swing.JLabel viewEmail;
    private javax.swing.JLabel viewEmail2;
    private javax.swing.JLabel viewLastname;
    private javax.swing.JLabel viewName;
    private javax.swing.JLabel viewNuid;
    private javax.swing.JPanel viewPanel;
    private javax.swing.JLabel viewPhone;
    private javax.swing.JLabel viewPhone2;
    private javax.swing.JLabel viewStreet;
    private javax.swing.JLabel viewStreet2;
    private javax.swing.JLabel viewZip;
    private javax.swing.JLabel viewZip2;
    // End of variables declaration//GEN-END:variables
}
